In [1]:
import numpy as np

In [2]:
v = np.array([5,8,9,3])
v

array([5, 8, 9, 3])

In [3]:
b = np.array([4,7,9,1])
b

array([4, 7, 9, 1])

In [4]:
v[1]

8

In [5]:
b[3]

1

In [6]:
v[1:3]

array([8, 9])

In [8]:
v[0:3]

array([5, 8, 9])

In [9]:
v[-2:]

array([9, 3])

In [10]:
v[-2:-1]

array([9])

In [11]:
v[-2:-5]

array([], dtype=int32)

In [12]:
v[-4:-1]

array([5, 8, 9])

In [15]:
print(v[2] + v[3])

12


In [13]:
v = np.array([5,8,9,3])
v

array([5, 8, 9, 3])

In [19]:
n = np.array([[4,6,8],[2,8,2]])

print(n)
print()

n[1,1]

[[4 6 8]
 [2 8 2]]



8

In [17]:
n[0,2]

8

In [20]:
k = np.array([[[4,6,8,9],[3,1,2,4]],[[3,6,8,9],[1,3,7,9]]])
k

array([[[4, 6, 8, 9],
        [3, 1, 2, 4]],

       [[3, 6, 8, 9],
        [1, 3, 7, 9]]])

In [21]:
k[0]

array([[4, 6, 8, 9],
       [3, 1, 2, 4]])

In [22]:
k[1]

array([[3, 6, 8, 9],
       [1, 3, 7, 9]])

In [23]:
k[0,1,2]

2

In [24]:
v = np.array([5,8,9,3])
v

array([5, 8, 9, 3])

In [25]:
type(v)

numpy.ndarray

In [26]:
v.dtype

dtype('int32')

In [27]:
v = np.array([5,8,9,3] , dtype = "int64")
v

array([5, 8, 9, 3], dtype=int64)

In [28]:
v.dtype

dtype('int64')

In [29]:
g = np.array([[4,7,9],[3,1]])
g

C:\Users\Tops\AppData\Local\Temp\ipykernel_2264\1699785385.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  g = np.array([[4,7,9],[3,1]])


array([list([4, 7, 9]), list([3, 1])], dtype=object)

In [30]:
type(g)

numpy.ndarray

In [31]:
g.dtype

dtype('O')

In [32]:
g = np.array([[4,7,9],[3,1,7]])
g

array([[4, 7, 9],
       [3, 1, 7]])

In [33]:
print(type(g))
print(g.dtype)

<class 'numpy.ndarray'>
int32


In [34]:
m = np.array([4,7,9,1])
print(m)
print(m.shape)

[4 7 9 1]
(4,)


In [36]:
t = np.array([[4,7,9],[1,3,7]])
print(t)
print(t.shape)

[[4 7 9]
 [1 3 7]]
(2, 3)


In [38]:
t = np.array([[[4,7,9],[1,3,7]]])
print(t)
print()
print(t.shape)

[[[4 7 9]
  [1 3 7]]]

(1, 2, 3)


In [41]:
t = np.array([[[4,7,9,6,6],[1,3,7,2,3]],[[5,7,9,3,1],[2,4,6,5,8]]])
print(t)
print()
print(t.shape)

[[[4 7 9 6 6]
  [1 3 7 2 3]]

 [[5 7 9 3 1]
  [2 4 6 5 8]]]

(2, 2, 5)


In [47]:
t = np.array([[4,7,9],[1,3,7]])
print(t)
print()
print("shape:" ,t.shape)
print()
print(t.reshape(2,3))

[[4 7 9]
 [1 3 7]]

shape: (2, 3)

[[4 7 9]
 [1 3 7]]


In [48]:
t

array([[4, 7, 9],
       [1, 3, 7]])

In [49]:
t.reshape(3,2)

array([[4, 7],
       [9, 1],
       [3, 7]])

In [50]:
t.reshape(1,6)

array([[4, 7, 9, 1, 3, 7]])

In [52]:
t.reshape(6,1)

array([[4],
       [7],
       [9],
       [1],
       [3],
       [7]])